export * from './domain/index.js';
export * from './state/index.js';
export * from './parser-bridge/index.js';
export * from './layout/index.js';
export * from './render-svg/index.js';
export * from './grid/index.js';
export * from './editor/index.js';
export * from './plugins/index.js';

export { createEditor, type EditorInstance, type EditorOptions, type EditorEvent, type EditorEventType, type EventHandler, type InsertMode } from './editor/index.js';
export { createStore, type EditorStore } from './state/index.js';
export { buildLayout, computeBounds, type LayoutOptions, DEFAULT_LAYOUT_OPTIONS } from './layout/index.js';
export { createAdapter, type CircuitParserAdapter, type StrictOptions, parseBoukamp, serialize, validate, validateParameterValues, tokenize, ElementRegistry, assignParamOffsets, parameterCount } from './parser-bridge/index.js';
export { renderCircuit, renderCircuitToElement, extractSvgString, renderCircuitEx, renderDocument, extractSvgSnapshot, exportSvgWithStyles, renderDslPreviewSvg, renderDslToSvg, buildCircuitLayers, collectInvalidElementIds, buildInfiniteGridLayer, buildEditorSvgShell, type SvgRenderOptions, type RenderOptions, type InteractionOverlay, type DslPreviewOptions, type ConnectionStyle } from './render-svg/index.js';
export { createCircuitGrid, importSpectrozCatalog, type CircuitGridOptions, type CircuitGridInstance, type GridColumnDef } from './grid/index.js';
export { DEFAULT_THEME, DARK_THEME, getTheme, toggleTheme, buildThemeCSS, buildPreviewThemeCSS, buildElementStrokeCSS, ELEMENT_STROKE_COLORS, type RenderTheme, type ThemeColors, type ThemeMode, type SymbolColorMode, type ThemeCSSOptions } from './render-svg/index.js';
export { createViewportController, parseWheelZoom, parsePointerPan, getZoomLevelLabel, type ViewportController } from './render-svg/index.js';
export { buildEquationEditorHTML, buildEquationEditorCSS, astToChips, attachEquationEditorEvents, type EquationEditorConfig } from './editor/dsl-equation-editor.js';
export { buildContextMenuHTML, buildContextMenuCSS } from './editor/interaction.js';
export type { ParseError } from './parser-bridge/parser.js';
export { allPlugins, minimalPlugins } from './plugins/index.js';
export type { EditorPlugin, PluginContext } from './plugins/types.js';